import { User } from 'src/user/entities/user.entity';
import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, CreateDateColumn, UpdateDateColumn } from 'typeorm';

@Entity('exams')
export class Exam {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  exam_title: string;

  @Column()
  subject: string;

  @Column({ nullable: true })
  topic: string;

  @Column({ default: 'medium' })
  difficulty: string;

  @Column({ default: 'en' })
  language: string;

  // Store the full exam structure (generated by AI) as JSON
  @Column({ type: 'jsonb' })
  questions: any; // Could define ExamQuestion[] interface later

  @Column({ default: 0 })
  totalQuestions: number;

  @Column({ default: 0 })
  correctAnswers: number;

  @Column({ default: 0 })
  wrongAnswers: number;

  @Column({ default: 0 })
  score: number;

  @Column({ default: false })
  completed: boolean;

  @ManyToOne(() => User, { onDelete: 'CASCADE', nullable: true })
  user: User;

  @Column({ nullable: true })
  spentTime: number;

  @Column({ nullable: true })
  duration_minutes: number;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}