import { User } from 'src/user/entities/user.entity';
import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, CreateDateColumn, UpdateDateColumn } from 'typeorm';

@Entity('quizzes')
export class Quiz {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  subject: string;

  @Column({ nullable: true })
  topic: string;

  @Column({ default: 'medium' })
  difficulty: string;

  @Column()
  language: string;

  // Store the full quiz structure (generated by AI) as JSON
  @Column({ type: 'jsonb' })
  questions: any; // Or define a TypeScript interface for stricter typing

  @Column({ default: false })
  done: boolean;

  @ManyToOne(() => User, { onDelete: 'CASCADE', nullable: true })
  user: User;

  @Column({ nullable: true })
  correctAnswer: number;

  @Column({ nullable: true })
  wrongAnswer: number;

  @Column({ nullable: true })
  spentTime: number;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}